.\" Copyright © 2017 Arianne,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH STENDHAL-NOBLOOD 6 "November  6 2017"
.SH NAME stendhal-noblood \- Child friendly version of the Stendhal MMORPG client
.SH SYNOPSIS
.B stendhal-noblood
.SH DESCRIPTION
\fBStendhal is a fun, friendly, & free multiplayer online adventure game with an old school feel.
